trigger:
 branches:
   include:
     - '*'
   exclude:
     - '*release*'
#     - '*feature*'

pool:
  name: "SEBA Azure Self-hosted"

steps:
- script: make live_create
  displayName: 'Build live ISO'
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: ''
    addBaseImageData: false
    containerRegistry: docker.tech.seba.cloud
    repository: $(repositoryBase)/$(applicationName)
    tags: $(version)

