[package]
name = "bdk-reserves-web"
version = "0.1.6"
edition = "2021"

[dependencies]
actix-web = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bdk = "0.28"
bdk-reserves = "0.28"
env_logger = "0.10"
log = "0.4"
base64 = "^0.13"

[dev-dependencies]
actix-rt = "1"