name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          changelog: CHANGELOG.md
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: make dir
      run: mkdir app
    - name: copy
      run: cp ./target/release/bdk-reserves-web ./app/


  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: bdk-reserves-web
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # key from repository secrets
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # name of the Heroku app
          heroku_app_name: "bdk-reserves-web"
          # app directory
          appdir: "./app"
          # start command
          procfile: "web: ./bdk-reserves-web"
          # email from which the app is uploaded
          heroku_email: "richi+heroku@ulrichard.ch"
          # buildpack is like environment used to run the app
          buildpack: "https://github.com/ph3nx/heroku-binary-buildpack.git"